options:
  docker: true

pipelines:
  branches:
    Test-Pipeline:
      - step:
          name: Build and Test
          script:
            - echo "Setting up environment for Build and Test for the Backend"
            # Copy .env.example to .env
            - cp .env.example .env
            # Install dependencies in the vendor folder
            - docker run --rm \
              -u "$(id -u):$(id -g)" \
              -v "$(pwd):/var/www/html" \
              -w /var/www/html \
              laravelsail/php83-composer:latest \
              composer install --ignore-platform-reqs
            # Start Sail services in detached mode
            - ./vendor/bin/sail up -d
            # Wait until the app is ready
            - ./vendor/bin/sail exec app bash -c 'until nc -z localhost 80; do sleep 1; done'
            # Run tests
            - ./vendor/bin/phpunit
            # Stop and remove containers
            - ./vendor/bin/sail down
